"use client";

import { useEffect, useRef, useState } from "react";
import { PageHeader } from "@/components/ui";
import { ARCHITECTURE_MERMAID } from "@/lib/architecture";

const MVP_MAP: { layer: string; production: string; mvp: string }[] = [
  { layer: "Dashboard / API", production: "Next.js + FastAPI + Keycloak", mvp: "Next.js app with route handlers, cookie auth (demo user)" },
  { layer: "Scenario & persona library", production: "LangGraph persona state machines, generated by persona LLM", mvp: "14 hand-built scenarios covering happy-path, stress, grounding, compliance, safety, adversarial" },
  { layer: "Synthetic caller", production: "Kokoro/Piper TTS → audiomentations → Pipecat → SIP", mvp: "Text-level ASR degradation simulator (homophones, dropped words) + browser speech playback" },
  { layer: "Side-effect verification", production: "Tool-call log from the agent gateway / POS webhooks", mvp: "Implemented: judges verify create_booking / transfer_to_human / send_sms calls, not transcript claims" },
  { layer: "Grounding & rule judges", production: "KB retrieval + deterministic rules", mvp: "Implemented: menu, hours, AI disclosure, PCI read-back, escalation, injection" },
  { layer: "Tone judge", production: "LLM-as-judge (Llama/Qwen on vLLM), calibrated on human labels", mvp: "Heuristic by default; switches to LLM judge when LLM_API_KEY is set (any OpenAI-compatible endpoint)" },
  { layer: "External agents", production: "SIP call into the real phone line", mvp: "Implemented: any OpenAI-compatible endpoint with real latency measurement" },
  { layer: "CI gate", production: "GitHub Action + badge", mvp: "Implemented: POST /api/runs returns gate verdict; SVG badge endpoint" },
  { layer: "Production monitor", production: "Langfuse sampling → same judges → pgvector clustering", mvp: "Seeded 14-day drift story; one-click promote failure → regression scenario (persisted)" },
  { layer: "Storage", production: "PostgreSQL + pgvector, MinIO", mvp: "Browser localStorage (stateless server; deterministic seeded runs regenerate anywhere)" },
];

export default function ArchitecturePage() {
  const ref = useRef<HTMLDivElement>(null);
  const [err, setErr] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const mermaid = (await import("mermaid")).default;
        mermaid.initialize({
          startOnLoad: false,
          theme: "dark",
          themeVariables: { fontFamily: "var(--font-geist-sans)", primaryColor: "#182130", primaryBorderColor: "#22d3ee", lineColor: "#8b9bb0", primaryTextColor: "#e6edf3", clusterBkg: "#121821", clusterBorder: "#233044" },
          flowchart: { curve: "basis", nodeSpacing: 30, rankSpacing: 40 },
        });
        const { svg } = await mermaid.render("soundcheck-arch", ARCHITECTURE_MERMAID);
        if (!cancelled && ref.current) ref.current.innerHTML = svg;
      } catch (e) {
        setErr((e as Error).message);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div>
      <PageHeader
        title="Architecture"
        subtitle="Production architecture for Soundcheck, entirely on open-source components. The table below maps each layer to what is implemented in this MVP."
        actions={
          <button
            className="btn-ghost"
            onClick={async () => {
              await navigator.clipboard.writeText(ARCHITECTURE_MERMAID);
              setCopied(true);
              setTimeout(() => setCopied(false), 1500);
            }}
          >
            {copied ? "Copied!" : "Copy Mermaid source"}
          </button>
        }
      />
      <div className="card mb-6 max-h-[80vh] overflow-auto p-4">
        {err ? <pre className="mono text-xs text-rose-300">{err}</pre> : <div ref={ref} className="min-h-64 [&_svg]:mx-auto [&_svg]:h-auto [&_svg]:w-full [&_svg]:min-w-[1100px] [&_svg]:max-w-[1500px]" />}
      </div>

      <div className="card overflow-hidden">
        <table className="w-full text-sm">
          <thead className="bg-panel-2 text-left text-xs uppercase tracking-wide text-muted">
            <tr>
              <th className="px-4 py-2">Layer</th>
              <th className="px-4 py-2">Production design</th>
              <th className="px-4 py-2">In this MVP</th>
            </tr>
          </thead>
          <tbody>
            {MVP_MAP.map((m) => (
              <tr key={m.layer} className="border-t border-line/60 align-top">
                <td className="px-4 py-2.5 font-medium">{m.layer}</td>
                <td className="px-4 py-2.5 text-muted">{m.production}</td>
                <td className="px-4 py-2.5 text-ink/90">{m.mvp}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <details className="card mt-6 p-4">
        <summary className="cursor-pointer text-sm font-medium">Mermaid source</summary>
        <pre className="mono mt-3 overflow-auto text-[11px] leading-relaxed text-muted">{ARCHITECTURE_MERMAID}</pre>
      </details>
    </div>
  );
}
